version: "3.7"

services:
    web:
        image: nginx:latest
        volumes:
            - .:/var/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
    php-fpm:
        image: php:8-fpm
        volumes:
            - .:/var/app

